### GET request

GET http://localhost:8080/users

### POST request

POST http://localhost:8080/user

### PUT request

PUT http://localhost:8080/user

### DELETE request

DELETE http://localhost:8080/user